<?xml version="1.0" encoding="UTF-8"?>

<DeployAppMetadata>
  <Multilanguage>false</Multilanguage>
  <MasterId>1O5S4T2+VEY6</MasterId>
  <Id>1O5Z8OX1M5JM</Id>
  <DesignMetas>
    <DesignAppMeta>
      <DevType>2</DevType>
      <AppVersion>1.5.0</AppVersion>
      <Modifier>13466739</Modifier>
      <DataXml>
        <AppMetadata>
          <DevType>2</DevType>
          <Number>kdtest_lentong_test_ext</Number>
          <Id>1O5Z8OX1M5JM</Id>
          <ParentId>1O5S4T2+VEY6</ParentId>
          <MasterId>1O5S4T2+VEY6</MasterId>
          <AppElement>
            <AppElement>
              <Number>kdtest_lentong_test_ext</Number>
              <Id>1O5Z8OX1M5JM</Id>
            </AppElement>
          </AppElement>
          <InheritPath>1O5S4T2+VEY6</InheritPath>
        </AppMetadata>
      </DataXml>
      <Description></Description>
      <DbRoute>demo</DbRoute>
      <Isv>kdtest</Isv>
      <OpenType>0</OpenType>
      <AllUserApp>0</AllUserApp>
      <Number>kdtest_lentong_test_ext</Number>
      <IndustryId>0</IndustryId>
      <Id>1O5Z8OX1M5JM</Id>
      <Seq>3</Seq>
      <CreateDate>1623137927952</CreateDate>
      <MainFormType>0</MainFormType>
      <BizCloudID>1MCNR4F8A9RK</BizCloudID>
      <DependencyID></DependencyID>
      <Image>icons/pc/application/gongyingxietong_48_48.png</Image>
      <OrgFunc></OrgFunc>
      <Visible>1</Visible>
      <ModifyDate>1625197045974</ModifyDate>
      <Dependency></Dependency>
      <HelpURL></HelpURL>
      <Label></Label>
      <ModelType>AppModel</ModelType>
      <MainFormName>lentong_test_应用首页</MainFormName>
      <ParentId>1O5S4T2+VEY6</ParentId>
      <BackImage></BackImage>
      <HomeURL></HomeURL>
      <MasterId>1O5S4T2+VEY6</MasterId>
      <Creater>1173835795551774720</Creater>
      <MainFormID>1O5S4TL221I6</MainFormID>
      <SimpleNumber></SimpleNumber>
      <InheritPath>1O5S4T2+VEY6</InheritPath>
      <RefAppId></RefAppId>
      <UserType>1</UserType>
      <DeployStatus>2</DeployStatus>
    </DesignAppMeta>
  </DesignMetas>
  <BOSVersion>1.0</BOSVersion>
</DeployAppMetadata>
