<?xml version="1.0" encoding="UTF-8"?>

<DeployMetadata>
  <Id>1132559434485071872</Id>
  <DesignMetas>
    <DesignConvertRuleMeta>
      <DevType>0</DevType>
      <ModifyDate>1619404356000</ModifyDate>
      <DataXml>
        <ConvertRuleMetadata>
          <DevType>0</DevType>
          <Isv>test</Isv>
          <ParentId/>
          <MasterId/>
          <BizappId>1J2RN1N6V4BB</BizappId>
          <RuleElement>
            <ConvertRuleElement>
              <FieldMapPolicy>
                <FieldMapPolicy>
                  <FieldMaps>
                    <FieldMapItem>
                      <ConvertType>SourceField</ConvertType>
                      <TargetFieldKey>billno</TargetFieldKey>
                      <SourceFieldKey>billno</SourceFieldKey>
                      <SumType>First</SumType>
                    </FieldMapItem>
                    <FieldMapItem>
                      <ConvertType>SourceField</ConvertType>
                      <TargetFieldKey>test_textfield1</TargetFieldKey>
                      <SourceFieldKey>test_textfield1</SourceFieldKey>
                      <SumType>First</SumType>
                    </FieldMapItem>
                    <FieldMapItem>
                      <ConvertType>SourceField</ConvertType>
                      <TargetFieldKey>test_qtyfield</TargetFieldKey>
                      <SourceFieldKey>test_qtyfield</SourceFieldKey>
                      <SumType>First</SumType>
                    </FieldMapItem>
                    <FieldMapItem>
                      <ConvertType>SourceField</ConvertType>
                      <TargetFieldKey>test_unitfield</TargetFieldKey>
                      <SourceFieldKey>test_unitfield</SourceFieldKey>
                      <SumType>First</SumType>
                    </FieldMapItem>
                  </FieldMaps>
                </FieldMapPolicy>
              </FieldMapPolicy>
              <FilterPolicy>
                <FilterPolicy>
                  <Condition>
                    <CRCondition>
                      <FilterString>{"filterRow":[],"forList":false}</FilterString>
                      <Description/>
                      <ExprTran/>
                    </CRCondition>
                  </Condition>
                </FilterPolicy>
              </FilterPolicy>
              <LinkEntityPolicy>
                <LinkEntityPolicy>
                  <SourceSubEntryKey/>
                  <TargetEntryKey>test_entryentity</TargetEntryKey>
                  <TargetSubEntryKey/>
                  <SourceEntryKey>test_entryentity</SourceEntryKey>
                  <LinkType>Link</LinkType>
                </LinkEntityPolicy>
              </LinkEntityPolicy>
              <efRule>false</efRule>
              <TargetEntityNumber>test_botp002</TargetEntityNumber>
              <GroupByPolicy>
                <GroupByPolicy>
                  <GroupByField/>
                  <GroupMode3>OneToOne</GroupMode3>
                  <GroupMode2>OneToOne</GroupMode2>
                  <GroupByField2/>
                  <GroupByField3/>
                  <GroupMode>OneToOne</GroupMode>
                </GroupByPolicy>
              </GroupByPolicy>
              <Name>转换规则-单据体</Name>
              <SourceEntityNumber>test_botp001</SourceEntityNumber>
              <Id>1132559434485071872</Id>
            </ConvertRuleElement>
          </RuleElement>
          <Id>1132559434485071872</Id>
          <InheritPath/>
          <CreateDate>1618211605000</CreateDate>
        </ConvertRuleMetadata>
      </DataXml>
      <ModifierId>1133252311779377152</ModifierId>
      <ModelType>ConvertRuleModel</ModelType>
      <Isv>test</Isv>
      <Version>1619404355851</Version>
      <ParentId></ParentId>
      <MasterId></MasterId>
      <BizappId>1J2RN1N6V4BB</BizappId>
      <TargetEntityNumber>test_botp002</TargetEntityNumber>
      <SourceEntityNumber>test_botp001</SourceEntityNumber>
      <Id>1132559434485071872</Id>
      <InheritPath></InheritPath>
      <CreateDate>1618211605000</CreateDate>
    </DesignConvertRuleMeta>
  </DesignMetas>
  <BOSVersion>1.0</BOSVersion>
</DeployMetadata>
