<?xml version="1.0" encoding="UTF-8"?>

<DeployMetadata>
  <Id>1132536789286780928</Id>
  <DesignMetas>
    <DesignConvertRuleMeta>
      <DevType>0</DevType>
      <ModifyDate>1619404356000</ModifyDate>
      <DataXml>
        <ConvertRuleMetadata>
          <DevType>0</DevType>
          <Isv>test</Isv>
          <ParentId/>
          <MasterId/>
          <BizappId>1J2RN1N6V4BB</BizappId>
          <RuleElement>
            <ConvertRuleElement>
              <FieldMapPolicy>
                <FieldMapPolicy>
                  <FieldMaps>
                    <FieldMapItem>
                      <ConvertType>SourceField</ConvertType>
                      <TargetFieldKey>billno</TargetFieldKey>
                      <SourceFieldKey>billno</SourceFieldKey>
                      <SumType>First</SumType>
                    </FieldMapItem>
                    <FieldMapItem>
                      <ConvertType>SourceField</ConvertType>
                      <TargetFieldKey>test_textfield</TargetFieldKey>
                      <SourceFieldKey>test_textfield</SourceFieldKey>
                      <SumType>First</SumType>
                    </FieldMapItem>
                    <FieldMapItem>
                      <ConvertType>SourceField</ConvertType>
                      <TargetFieldKey>test_integerfield</TargetFieldKey>
                      <SourceFieldKey>test_integerfield</SourceFieldKey>
                      <SumType>First</SumType>
                    </FieldMapItem>
                    <FieldMapItem>
                      <ConvertType>SourceField</ConvertType>
                      <TargetFieldKey>test_decimalfield</TargetFieldKey>
                      <SourceFieldKey>test_decimalfield</SourceFieldKey>
                      <SumType>First</SumType>
                    </FieldMapItem>
                    <FieldMapItem>
                      <ConvertType>SourceField</ConvertType>
                      <TargetFieldKey>test_largetextfield</TargetFieldKey>
                      <SourceFieldKey>test_largetextfield</SourceFieldKey>
                      <SumType>First</SumType>
                    </FieldMapItem>
                    <FieldMapItem>
                      <ConvertType>SourceField</ConvertType>
                      <TargetFieldKey>test_datefield</TargetFieldKey>
                      <SourceFieldKey>test_datefield</SourceFieldKey>
                      <SumType>First</SumType>
                    </FieldMapItem>
                    <FieldMapItem>
                      <ConvertType>SourceField</ConvertType>
                      <TargetFieldKey>test_datetimefield</TargetFieldKey>
                      <SourceFieldKey>test_datetimefield</SourceFieldKey>
                      <SumType>First</SumType>
                    </FieldMapItem>
                    <FieldMapItem>
                      <ConvertType>SourceField</ConvertType>
                      <TargetFieldKey>test_daterangefield_startdate</TargetFieldKey>
                      <SourceFieldKey>test_daterangefield_startdate</SourceFieldKey>
                      <SumType>First</SumType>
                    </FieldMapItem>
                    <FieldMapItem>
                      <ConvertType>SourceField</ConvertType>
                      <TargetFieldKey>test_daterangefield_enddate</TargetFieldKey>
                      <SourceFieldKey>test_daterangefield_enddate</SourceFieldKey>
                      <SumType>First</SumType>
                    </FieldMapItem>
                    <FieldMapItem>
                      <ConvertType>SourceField</ConvertType>
                      <TargetFieldKey>test_timefield</TargetFieldKey>
                      <SourceFieldKey>test_timefield</SourceFieldKey>
                      <SumType>First</SumType>
                    </FieldMapItem>
                    <FieldMapItem>
                      <ConvertType>SourceField</ConvertType>
                      <TargetFieldKey>fskkkkkkkkkkk</TargetFieldKey>
                      <SourceFieldKey>test_timerangefield_starttime</SourceFieldKey>
                      <SumType>First</SumType>
                    </FieldMapItem>
                    <FieldMapItem>
                      <ConvertType>SourceField</ConvertType>
                      <TargetFieldKey>fsjjjjjjjjjjjj</TargetFieldKey>
                      <SourceFieldKey>test_timerangefield_endtime</SourceFieldKey>
                      <SumType>First</SumType>
                    </FieldMapItem>
                    <FieldMapItem>
                      <ConvertType>SourceField</ConvertType>
                      <TargetFieldKey>test_combofield</TargetFieldKey>
                      <SourceFieldKey>test_combofield</SourceFieldKey>
                      <SumType>First</SumType>
                    </FieldMapItem>
                    <FieldMapItem>
                      <ConvertType>SourceField</ConvertType>
                      <TargetFieldKey>test_mulcombofield</TargetFieldKey>
                      <SourceFieldKey>test_mulcombofield</SourceFieldKey>
                      <SumType>First</SumType>
                    </FieldMapItem>
                    <FieldMapItem>
                      <ConvertType>SourceField</ConvertType>
                      <TargetFieldKey>test_stepperfield</TargetFieldKey>
                      <SourceFieldKey>test_stepperfield</SourceFieldKey>
                      <SumType>First</SumType>
                    </FieldMapItem>
                    <FieldMapItem>
                      <ConvertType>SourceField</ConvertType>
                      <TargetFieldKey>test_cityfield</TargetFieldKey>
                      <SourceFieldKey>test_cityfield</SourceFieldKey>
                      <SumType>First</SumType>
                    </FieldMapItem>
                    <FieldMapItem>
                      <ConvertType>SourceField</ConvertType>
                      <TargetFieldKey>test_admindivisionfield</TargetFieldKey>
                      <SourceFieldKey>test_admindivisionfield</SourceFieldKey>
                      <SumType>First</SumType>
                    </FieldMapItem>
                    <FieldMapItem>
                      <ConvertType>SourceField</ConvertType>
                      <TargetFieldKey>test_mulbasedatafield</TargetFieldKey>
                      <SourceFieldKey>test_mulbasedatafield</SourceFieldKey>
                      <SumType>First</SumType>
                    </FieldMapItem>
                    <FieldMapItem>
                      <ConvertType>SourceField</ConvertType>
                      <TargetFieldKey>test_basedatafield</TargetFieldKey>
                      <SourceFieldKey>test_basedatafield</SourceFieldKey>
                      <SumType>First</SumType>
                    </FieldMapItem>
                    <FieldMapItem>
                      <ConvertType>SourceField</ConvertType>
                      <TargetFieldKey>test_flexfield</TargetFieldKey>
                      <SourceFieldKey>test_flexfield</SourceFieldKey>
                      <SumType>First</SumType>
                    </FieldMapItem>
                  </FieldMaps>
                </FieldMapPolicy>
              </FieldMapPolicy>
              <FilterPolicy>
                <FilterPolicy>
                  <Condition>
                    <CRCondition>
                      <FilterString>{"filterRow":[],"forList":false}</FilterString>
                      <Description/>
                      <ExprTran/>
                    </CRCondition>
                  </Condition>
                </FilterPolicy>
              </FilterPolicy>
              <LinkEntityPolicy>
                <LinkEntityPolicy>
                  <TargetEntryKey>test_botp002</TargetEntryKey>
                  <SourceEntryKey>test_botp001</SourceEntryKey>
                  <LinkType>Link</LinkType>
                </LinkEntityPolicy>
              </LinkEntityPolicy>
              <efRule>false</efRule>
              <TargetEntityNumber>test_botp002</TargetEntityNumber>
              <GroupByPolicy>
                <GroupByPolicy>
                  <GroupByField/>
                  <GroupMode3>OneToOne</GroupMode3>
                  <GroupMode2>OneToOne</GroupMode2>
                  <GroupByField2/>
                  <GroupByField3/>
                  <GroupMode>OneToOne</GroupMode>
                </GroupByPolicy>
              </GroupByPolicy>
              <Name>转换规则-单据头</Name>
              <SourceEntityNumber>test_botp001</SourceEntityNumber>
              <Id>1132536789286780928</Id>
            </ConvertRuleElement>
          </RuleElement>
          <Id>1132536789286780928</Id>
          <InheritPath/>
          <CreateDate>1618208906000</CreateDate>
        </ConvertRuleMetadata>
      </DataXml>
      <ModifierId>1133252311779377152</ModifierId>
      <ModelType>ConvertRuleModel</ModelType>
      <Isv>test</Isv>
      <Version>1619404355907</Version>
      <ParentId></ParentId>
      <MasterId></MasterId>
      <BizappId>1J2RN1N6V4BB</BizappId>
      <TargetEntityNumber>test_botp002</TargetEntityNumber>
      <SourceEntityNumber>test_botp001</SourceEntityNumber>
      <Id>1132536789286780928</Id>
      <InheritPath></InheritPath>
      <CreateDate>1618208906000</CreateDate>
    </DesignConvertRuleMeta>
  </DesignMetas>
  <BOSVersion>1.0</BOSVersion>
</DeployMetadata>
