<?xml version="1.0" encoding="UTF-8"?>

<DeployAppMetadata>
  <Multilanguage>false</Multilanguage>
  <MasterId>1JF7N38+XB/P</MasterId>
  <Id>1JF7N38+XB/P</Id>
  <DesignMetas>
    <DesignAppMeta>
      <DevType>0</DevType>
      <AppVersion>2.0.038.0</AppVersion>
      <Modifier>1133252311779377152</Modifier>
      <DataXml>
        <AppMetadata>
          <DevType>0</DevType>
          <AppFunctionPackets>
            <AppFunctionPacketElement>
              <Number>MainPage</Number>
              <Name>首页</Name>
              <Description/>
              <Id>1JF7N5MF1LM2</Id>
              <Leaf>0</Leaf>
              <ParentId/>
              <Seq>1</Seq>
            </AppFunctionPacketElement>
          </AppFunctionPackets>
          <AppMenus>
            <AppMenuElement>
              <FormId>/9ZLSWRJE1Z2</FormId>
              <IconShortcut>/icons/pc/application/tysj4_48_48.png</IconShortcut>
              <Visible>true</Visible>
              <Description/>
              <ParentId>1JF7N38+XB/P</ParentId>
              <OpenType>MainNewTabPage</OpenType>
              <VectorImage>kdfont kdfont-cebianlantubiao1beifen</VectorImage>
              <Number>ee9e3bfeac</Number>
              <FormName>出差情况</FormName>
              <FormNumber>tra_tripinfo</FormNumber>
              <Parameter/>
              <Name>yyy</Name>
              <Id>1135527932773532672</Id>
              <Seq>1</Seq>
            </AppMenuElement>
            <AppMenuElement>
              <FormId>/WXHVRP15OWF</FormId>
              <IconShortcut>/icons/pc/entrance/helpcentre.png</IconShortcut>
              <Visible>0</Visible>
              <Caption>帮助中心</Caption>
              <Description>帮助中心</Description>
              <ParentId>1JF7N38+XB/P</ParentId>
              <VectorImage>kdfont kdfont-tishixinxi_l</VectorImage>
              <FormName>应用入门中心</FormName>
              <FormNumber>bas_appstarted</FormNumber>
              <Parameter>{"caption":{"zh_CN":"帮助中心"}}</Parameter>
              <Name>帮助中心</Name>
              <Id>1JG046GN/H7#hpce</Id>
              <Seq>32766</Seq>
            </AppMenuElement>
          </AppMenus>
          <Isv>test</Isv>
          <Number>test_qing</Number>
          <Id>1JF7N38+XB/P</Id>
          <BizCloudID>WR/+=X74SFD</BizCloudID>
          <ParentId/>
          <MasterId/>
          <AppElement>
            <AppElement>
              <MainFormNumber>test_qing_apphome</MainFormNumber>
              <Description/>
              <DbRoute>secd</DbRoute>
              <OpenType>0</OpenType>
              <AllUserApp>0</AllUserApp>
              <Number>test_qing</Number>
              <Id>1JF7N38+XB/P</Id>
              <Seq>109</Seq>
              <MainFormType>0</MainFormType>
              <DependencyID/>
              <Image>icons/pc/application/gongyingxietong_48_48.png</Image>
              <Visible>1</Visible>
              <Dependency/>
              <HelpURL/>
              <Label/>
              <MainFormName>青_应用首页</MainFormName>
              <Version>2.0.038.0</Version>
              <BackImage/>
              <HomeURL/>
              <MainFormID>1JF7NGT5KKJ=</MainFormID>
              <Name>青</Name>
              <SimpleNumber/>
              <UserType>1</UserType>
              <DeployStatus>2</DeployStatus>
            </AppElement>
          </AppElement>
          <InheritPath/>
        </AppMetadata>
      </DataXml>
      <Description></Description>
      <DbRoute>secd</DbRoute>
      <Isv>test</Isv>
      <OpenType>0</OpenType>
      <AllUserApp>0</AllUserApp>
      <Number>test_qing</Number>
      <IndustryId>0</IndustryId>
      <Id>1JF7N38+XB/P</Id>
      <Seq>109</Seq>
      <CreateDate>1618541325000</CreateDate>
      <MainFormType>0</MainFormType>
      <BizCloudID>WR/+=X74SFD</BizCloudID>
      <DependencyID></DependencyID>
      <Image>icons/pc/application/gongyingxietong_48_48.png</Image>
      <OrgFunc></OrgFunc>
      <Visible>1</Visible>
      <ModifyDate>1618565478000</ModifyDate>
      <Dependency></Dependency>
      <HelpURL></HelpURL>
      <Label></Label>
      <ModelType>AppModel</ModelType>
      <MainFormName>青_应用首页</MainFormName>
      <ParentId></ParentId>
      <BackImage></BackImage>
      <HomeURL></HomeURL>
      <MasterId></MasterId>
      <Creater>1128310777833326592</Creater>
      <MainFormID>1JF7NGT5KKJ=</MainFormID>
      <SimpleNumber></SimpleNumber>
      <InheritPath></InheritPath>
      <RefAppId></RefAppId>
      <UserType>1</UserType>
      <DeployStatus>2</DeployStatus>
    </DesignAppMeta>
  </DesignMetas>
  <BOSVersion>1.0</BOSVersion>
</DeployAppMetadata>
