<?xml version="1.0" encoding="UTF-8"?>

<DeployAppMetadata>
  <Multilanguage>false</Multilanguage>
  <MasterId>15RV9A+TRZ0D</MasterId>
  <Id>15RV9A+TRZ0D</Id>
  <DesignMetas>
    <DesignAppMeta>
      <DevType>0</DevType>
      <AppVersion>1.5.0</AppVersion>
      <Modifier>74900085</Modifier>
      <DataXml>
        <AppMetadata>
          <DevType>0</DevType>
          <AppFunctionPackets>
            <AppFunctionPacketElement>
              <Number>MainPage</Number>
              <Name>首页</Name>
              <Description/>
              <Id>15RV9A0RXO25</Id>
              <Leaf>0</Leaf>
              <ParentId/>
              <Seq>1</Seq>
            </AppFunctionPacketElement>
            <AppFunctionPacketElement>
              <Number>attachment_test</Number>
              <Name>附件测试</Name>
              <Description/>
              <Id>15RWO9E76+M+</Id>
              <Leaf>false</Leaf>
              <ParentId/>
              <Seq>2</Seq>
            </AppFunctionPacketElement>
            <AppFunctionPacketElement>
              <Number>import_test</Number>
              <Name>引入引出测试</Name>
              <Description/>
              <Id>15S+PJO0OXFW</Id>
              <Leaf>false</Leaf>
              <ParentId/>
              <Seq>3</Seq>
            </AppFunctionPacketElement>
            <AppFunctionPacketElement>
              <Number>param_test</Number>
              <Name>参数测试</Name>
              <Description/>
              <Id>15W42TRM8XFN</Id>
              <Leaf>false</Leaf>
              <ParentId/>
              <Seq>4</Seq>
            </AppFunctionPacketElement>
          </AppFunctionPackets>
          <AppMenus>
            <AppMenuElement>
              <IconShortcut>/icons/pc/application/tysj_48_48.png</IconShortcut>
              <Visible>true</Visible>
              <Description/>
              <ParentId>1144024199841451008</ParentId>
              <OpenType>MainNewTabPage</OpenType>
              <VectorImage>kdfont kdfont-tongyongtubiao3</VectorImage>
              <Number>d1051b270a</Number>
              <Parameter/>
              <Name/>
              <Id>1144024701933193216</Id>
            </AppMenuElement>
            <AppMenuElement>
              <IconShortcut>/icons/pc/application/tysj3_48_48.png</IconShortcut>
              <Visible>true</Visible>
              <Description/>
              <ParentId>15RV9A+TRZ0D</ParentId>
              <OpenType>MainNewTabPage</OpenType>
              <VectorImage>kdfont kdfont-tongyongtubiao5</VectorImage>
              <Number>4493a65276</Number>
              <Parameter/>
              <Name/>
              <Id>1144024199841451008</Id>
              <Seq>1</Seq>
            </AppMenuElement>
            <AppMenuElement>
              <IconShortcut>/icons/pc/application/tysj2_48_48.png</IconShortcut>
              <Visible>true</Visible>
              <Description/>
              <ParentId>1144024701933193216</ParentId>
              <OpenType>MainNewTabPage</OpenType>
              <VectorImage>kdfont kdfont-tongyongtubiao4</VectorImage>
              <Number>b5a1dd858e</Number>
              <Parameter/>
              <Name/>
              <Id>1144040351258905600</Id>
              <Seq>1</Seq>
            </AppMenuElement>
            <AppMenuElement>
              <IconShortcut>/icons/pc/application/tysj5_48_48.png</IconShortcut>
              <Visible>true</Visible>
              <Description/>
              <ParentId>1144024199841451008</ParentId>
              <OpenType>MainNewTabPage</OpenType>
              <VectorImage>kdfont kdfont-cebianlantubiao6beifen</VectorImage>
              <Number>b39a42cb85</Number>
              <Parameter/>
              <Name/>
              <Id>1144026995521227776</Id>
              <Seq>2</Seq>
            </AppMenuElement>
            <AppMenuElement>
              <IconShortcut>/icons/pc/application/tysj2_48_48.png</IconShortcut>
              <Visible>true</Visible>
              <Description/>
              <ParentId>15RV9A+TRZ0D</ParentId>
              <OpenType>MainNewTabPage</OpenType>
              <VectorImage>kdfont kdfont-tongyongtubiao4</VectorImage>
              <Number>29b10898b8</Number>
              <Parameter/>
              <Name/>
              <Id>1144039277852624896</Id>
              <Seq>2</Seq>
            </AppMenuElement>
            <AppMenuElement>
              <IconShortcut>/icons/pc/application/tysj4_48_48.png</IconShortcut>
              <Visible>true</Visible>
              <Description/>
              <ParentId>15RV9A+TRZ0D</ParentId>
              <OpenType>MainNewTabPage</OpenType>
              <VectorImage>kdfont kdfont-cebianlantubiao1beifen</VectorImage>
              <Number>9597079646</Number>
              <Parameter/>
              <Name/>
              <Id>1144107043997615104</Id>
              <Seq>4</Seq>
            </AppMenuElement>
            <AppMenuElement>
              <FormId>/WXHVRP15OWF</FormId>
              <IconShortcut>/icons/pc/entrance/helpcentre.png</IconShortcut>
              <Visible>0</Visible>
              <Caption>帮助中心</Caption>
              <Description>帮助中心</Description>
              <ParentId>15RV9A+TRZ0D</ParentId>
              <VectorImage>kdfont kdfont-tishixinxi_l</VectorImage>
              <FormName>应用入门中心</FormName>
              <FormNumber>bas_appstarted</FormNumber>
              <Parameter>{"caption":{"zh_CN":"帮助中心","zh_TW":"帮助中心_TW","en_US":"帮助中心"}}</Parameter>
              <Name>帮助中心</Name>
              <Id>18+WFZ+LEYX#hpce</Id>
              <Seq>32766</Seq>
            </AppMenuElement>
          </AppMenus>
          <Isv>kdtest</Isv>
          <Number>kdtest_chen_test1</Number>
          <Id>15RV9A+TRZ0D</Id>
          <BizCloudID>18Y2T5WS5AFV</BizCloudID>
          <ParentId/>
          <MasterId/>
          <AppElement>
            <AppElement>
              <MainFormNumber>kdtest_chen_test1_apphome</MainFormNumber>
              <Description/>
              <DbRoute>secd</DbRoute>
              <OpenType>0</OpenType>
              <AllUserApp>0</AllUserApp>
              <Number>kdtest_chen_test1</Number>
              <Id>15RV9A+TRZ0D</Id>
              <Seq>1</Seq>
              <MainFormType>0</MainFormType>
              <DependencyID/>
              <Image>icons/pc/application/gongyingxietong_48_48.png</Image>
              <OrgFunc/>
              <Visible>1</Visible>
              <Dependency/>
              <HelpURL/>
              <Label/>
              <MainFormName>陈凡测试_应用首页</MainFormName>
              <Version>1.5.0</Version>
              <BackImage/>
              <HomeURL/>
              <MainFormID>15RV9AOL1HUU</MainFormID>
              <Name>陈凡测试1</Name>
              <SimpleNumber/>
              <UserType>1</UserType>
              <DeployStatus>1</DeployStatus>
            </AppElement>
          </AppElement>
          <InheritPath/>
        </AppMetadata>
      </DataXml>
      <Description></Description>
      <DbRoute>secd</DbRoute>
      <Isv>kdtest</Isv>
      <OpenType>0</OpenType>
      <AllUserApp>0</AllUserApp>
      <Number>kdtest_chen_test1</Number>
      <IndustryId>0</IndustryId>
      <Id>15RV9A+TRZ0D</Id>
      <Seq>1</Seq>
      <CreateDate>1604299440000</CreateDate>
      <MainFormType>0</MainFormType>
      <BizCloudID>18Y2T5WS5AFV</BizCloudID>
      <DependencyID></DependencyID>
      <Image>icons/pc/application/gongyingxietong_48_48.png</Image>
      <OrgFunc></OrgFunc>
      <Visible>1</Visible>
      <ModifyDate>1626660440688</ModifyDate>
      <Dependency></Dependency>
      <HelpURL></HelpURL>
      <Label></Label>
      <ModelType>AppModel</ModelType>
      <MainFormName>陈凡测试_应用首页</MainFormName>
      <ParentId></ParentId>
      <BackImage></BackImage>
      <HomeURL></HomeURL>
      <MasterId></MasterId>
      <Creater>90875885</Creater>
      <MainFormID>15RV9AOL1HUU</MainFormID>
      <SimpleNumber></SimpleNumber>
      <InheritPath></InheritPath>
      <RefAppId></RefAppId>
      <UserType>1</UserType>
      <DeployStatus>1</DeployStatus>
    </DesignAppMeta>
  </DesignMetas>
  <BOSVersion>1.0</BOSVersion>
</DeployAppMetadata>
