<?xml version="1.0" encoding="UTF-8"?>

<DeployAppMetadata>
  <Multilanguage>false</Multilanguage>
  <MasterId>1JJE=2398M+Y</MasterId>
  <Id>1JJE=2398M+Y</Id>
  <DesignMetas>
    <DesignAppMeta>
      <DevType>0</DevType>
      <AppVersion>2.0.038.0</AppVersion>
      <Modifier>1132547836194325504</Modifier>
      <DataXml>
        <AppMetadata>
          <DevType>0</DevType>
          <AppFunctionPackets>
            <AppFunctionPacketElement>
              <Number>MainPage</Number>
              <Name>首页</Name>
              <Description/>
              <Id>1JJE=253RXV6</Id>
              <Leaf>0</Leaf>
              <ParentId/>
              <Seq>1</Seq>
            </AppFunctionPacketElement>
          </AppFunctionPackets>
          <AppMenus>
            <AppMenuElement>
              <FormId>1J2YJ0K6YQUL</FormId>
              <ParameterType>ListShowParameter</ParameterType>
              <IconShortcut>/icons/pc/application/tysj5_48_48.png</IconShortcut>
              <Visible>true</Visible>
              <Description/>
              <ParentId>1JJE=2398M+Y</ParentId>
              <OpenType>MainNewTabPage</OpenType>
              <VectorImage>kdfont kdfont-cebianlantubiao6beifen</VectorImage>
              <Number>45a7fa4d3a</Number>
              <FormName>基础资料0412</FormName>
              <FormNumber>test_jczl0412</FormNumber>
              <Parameter/>
              <Name>基础资料0412</Name>
              <Id>1136203317873999872</Id>
              <Seq>1</Seq>
            </AppMenuElement>
            <AppMenuElement>
              <FormId>/WXHVRP15OWF</FormId>
              <IconShortcut>/icons/pc/entrance/helpcentre.png</IconShortcut>
              <Visible>0</Visible>
              <Caption>帮助中心</Caption>
              <Description>帮助中心</Description>
              <ParentId>1JJE=2398M+Y</ParentId>
              <VectorImage>kdfont kdfont-tishixinxi_l</VectorImage>
              <FormName>应用入门中心</FormName>
              <FormNumber>bas_appstarted</FormNumber>
              <Parameter>{"caption":{"zh_CN":"帮助中心"}}</Parameter>
              <Name>帮助中心</Name>
              <Id>1JJEN3H2WWV#hpce</Id>
              <Seq>32766</Seq>
            </AppMenuElement>
          </AppMenus>
          <Isv>test</Isv>
          <Number>test_testa</Number>
          <Id>1JJE=2398M+Y</Id>
          <BizCloudID>WR/+=X74SFD</BizCloudID>
          <ParentId/>
          <MasterId/>
          <AppElement>
            <AppElement>
              <MainFormNumber>test_testa_apphome</MainFormNumber>
              <Description/>
              <DbRoute>secd</DbRoute>
              <OpenType>0</OpenType>
              <AllUserApp>0</AllUserApp>
              <Number>test_testa</Number>
              <Id>1JJE=2398M+Y</Id>
              <Seq>110</Seq>
              <MainFormType>0</MainFormType>
              <DependencyID/>
              <Image>icons/pc/application/gongyingxietong_48_48.png</Image>
              <Visible>1</Visible>
              <Dependency/>
              <HelpURL/>
              <Label/>
              <MainFormName>tests_应用首页</MainFormName>
              <Version>2.0.038.0</Version>
              <BackImage/>
              <HomeURL/>
              <MainFormID>1JJE=3230M1X</MainFormID>
              <Name>tests</Name>
              <SimpleNumber/>
              <UserType>1</UserType>
              <DeployStatus>2</DeployStatus>
            </AppElement>
          </AppElement>
          <InheritPath/>
        </AppMetadata>
      </DataXml>
      <Description></Description>
      <DbRoute>secd</DbRoute>
      <Isv>test</Isv>
      <OpenType>0</OpenType>
      <AllUserApp>0</AllUserApp>
      <Number>test_testa</Number>
      <IndustryId>0</IndustryId>
      <Id>1JJE=2398M+Y</Id>
      <Seq>110</Seq>
      <CreateDate>1618645728000</CreateDate>
      <MainFormType>0</MainFormType>
      <BizCloudID>WR/+=X74SFD</BizCloudID>
      <DependencyID></DependencyID>
      <Image>icons/pc/application/gongyingxietong_48_48.png</Image>
      <OrgFunc></OrgFunc>
      <Visible>1</Visible>
      <ModifyDate>1618645990000</ModifyDate>
      <Dependency></Dependency>
      <HelpURL></HelpURL>
      <Label></Label>
      <ModelType>AppModel</ModelType>
      <MainFormName>tests_应用首页</MainFormName>
      <ParentId></ParentId>
      <BackImage></BackImage>
      <HomeURL></HomeURL>
      <MasterId></MasterId>
      <Creater>1132547836194325504</Creater>
      <MainFormID>1JJE=3230M1X</MainFormID>
      <SimpleNumber></SimpleNumber>
      <InheritPath></InheritPath>
      <RefAppId></RefAppId>
      <UserType>1</UserType>
      <DeployStatus>2</DeployStatus>
    </DesignAppMeta>
  </DesignMetas>
  <BOSVersion>1.0</BOSVersion>
</DeployAppMetadata>
