<?xml version="1.0" encoding="UTF-8"?>

<DeployAppMetadata>
  <Multilanguage>false</Multilanguage>
  <MasterId>1J2RN1N6V4BB</MasterId>
  <Id>1J2RN1N6V4BB</Id>
  <DesignMetas>
    <DesignAppMeta>
      <DevType>0</DevType>
      <AppVersion>2.0.038.0</AppVersion>
      <Modifier>1133252311779377152</Modifier>
      <DataXml>
        <AppMetadata>
          <DevType>0</DevType>
          <AppFunctionPackets>
            <AppFunctionPacketElement>
              <Number>MainPage</Number>
              <Name>首页</Name>
              <Description/>
              <Id>1J2RN1OW3LTK</Id>
              <Leaf>0</Leaf>
              <ParentId/>
              <Seq>1</Seq>
            </AppFunctionPacketElement>
            <AppFunctionPacketElement>
              <Number>report</Number>
              <Name>报表</Name>
              <Description/>
              <Id>1J5WF5/J5CHG</Id>
              <Leaf>false</Leaf>
              <ParentId/>
              <Seq>2</Seq>
            </AppFunctionPacketElement>
            <AppFunctionPacketElement>
              <Number>billtype</Number>
              <Name>单据类型</Name>
              <Description/>
              <Id>1J9=P7B4ERN=</Id>
              <Leaf>false</Leaf>
              <ParentId/>
              <Seq>3</Seq>
            </AppFunctionPacketElement>
            <AppFunctionPacketElement>
              <Number>tanxingyu</Number>
              <Name>弹性域</Name>
              <Description/>
              <Id>1JBI=7IB9ETV</Id>
              <Leaf>false</Leaf>
              <ParentId/>
              <Seq>4</Seq>
            </AppFunctionPacketElement>
          </AppFunctionPackets>
          <AppMenus>
            <AppMenuElement>
              <FormId>1J2RQ9OYE+HT</FormId>
              <ParameterType>BillShowParameter</ParameterType>
              <IconShortcut>/icons/pc/application/tysj5_48_48.png</IconShortcut>
              <Visible>true</Visible>
              <Description/>
              <ParentId>1J2RN1N6V4BB</ParentId>
              <OpenType>MainNewTabPage</OpenType>
              <VectorImage>kdfont kdfont-cebianlantubiao6beifen</VectorImage>
              <Number>ec1f752897</Number>
              <FormName>botp001</FormName>
              <FormNumber>test_botp001</FormNumber>
              <Parameter/>
              <Name>liu</Name>
              <Id>1133264722682971136</Id>
              <Seq>1</Seq>
            </AppMenuElement>
            <AppMenuElement>
              <FormId>/WXHVRP15OWF</FormId>
              <IconShortcut>/icons/pc/entrance/helpcentre.png</IconShortcut>
              <Visible>0</Visible>
              <Caption>帮助中心</Caption>
              <Description>帮助中心</Description>
              <ParentId>1J2RN1N6V4BB</ParentId>
              <VectorImage>kdfont kdfont-tishixinxi_l</VectorImage>
              <FormName>应用入门中心</FormName>
              <FormNumber>bas_appstarted</FormNumber>
              <Parameter>{"caption":{"zh_CN":"帮助中心"}}</Parameter>
              <Name>帮助中心</Name>
              <Id>1J6BL4K0JBG#hpce</Id>
              <Seq>32766</Seq>
            </AppMenuElement>
          </AppMenus>
          <Isv>test</Isv>
          <Number>test_liu</Number>
          <Id>1J2RN1N6V4BB</Id>
          <BizCloudID>WR/+=X74SFD</BizCloudID>
          <ParentId/>
          <MasterId/>
          <AppElement>
            <AppElement>
              <MainFormNumber>test_liu_apphome</MainFormNumber>
              <Description/>
              <DbRoute>secd</DbRoute>
              <OpenType>0</OpenType>
              <AllUserApp>0</AllUserApp>
              <Number>test_liu</Number>
              <Id>1J2RN1N6V4BB</Id>
              <Seq>1</Seq>
              <MainFormType>0</MainFormType>
              <DependencyID/>
              <Image>icons/pc/application/gongyingxietong_48_48.png</Image>
              <Visible>1</Visible>
              <Dependency/>
              <HelpURL/>
              <Label/>
              <MainFormName>LIU_应用首页</MainFormName>
              <Version>2.0.038.0</Version>
              <BackImage/>
              <HomeURL/>
              <MainFormID>1J2RN29=+O85</MainFormID>
              <Name>LIU</Name>
              <SimpleNumber/>
              <UserType>1</UserType>
              <DeployStatus>2</DeployStatus>
            </AppElement>
          </AppElement>
          <InheritPath/>
        </AppMetadata>
      </DataXml>
      <Description></Description>
      <DbRoute>secd</DbRoute>
      <Isv>test</Isv>
      <OpenType>0</OpenType>
      <AllUserApp>0</AllUserApp>
      <Number>test_liu</Number>
      <IndustryId>0</IndustryId>
      <Id>1J2RN1N6V4BB</Id>
      <Seq>1</Seq>
      <CreateDate>1618206368000</CreateDate>
      <MainFormType>0</MainFormType>
      <BizCloudID>WR/+=X74SFD</BizCloudID>
      <DependencyID></DependencyID>
      <Image>icons/pc/application/gongyingxietong_48_48.png</Image>
      <OrgFunc></OrgFunc>
      <Visible>1</Visible>
      <ModifyDate>1618558740000</ModifyDate>
      <Dependency></Dependency>
      <HelpURL></HelpURL>
      <Label></Label>
      <ModelType>AppModel</ModelType>
      <MainFormName>LIU_应用首页</MainFormName>
      <ParentId></ParentId>
      <BackImage></BackImage>
      <HomeURL></HomeURL>
      <MasterId></MasterId>
      <Creater>1128310777833326592</Creater>
      <MainFormID>1J2RN29=+O85</MainFormID>
      <SimpleNumber></SimpleNumber>
      <InheritPath></InheritPath>
      <RefAppId></RefAppId>
      <UserType>1</UserType>
      <DeployStatus>2</DeployStatus>
    </DesignAppMeta>
  </DesignMetas>
  <BOSVersion>1.0</BOSVersion>
</DeployAppMetadata>
