<?xml version="1.0" encoding="UTF-8"?>

<DeployAppMetadata>
  <Multilanguage>false</Multilanguage>
  <MasterId>1J2YK+/SZ28M</MasterId>
  <Id>1J95XPMF5PN3</Id>
  <DesignMetas>
    <DesignAppMeta>
      <DevType>2</DevType>
      <AppVersion>1.5.0</AppVersion>
      <Modifier>1128310777833326592</Modifier>
      <DataXml>
        <AppMetadata>
          <DevType>2</DevType>
          <Number>test_chen_ext</Number>
          <Id>1J95XPMF5PN3</Id>
          <ParentId>1J2YK+/SZ28M</ParentId>
          <MasterId>1J2YK+/SZ28M</MasterId>
          <AppElement>
            <AppElement>
              <Number>test_chen_ext</Number>
              <Id>1J95XPMF5PN3</Id>
              <OrgFunc/>
              <Version>1.5.0</Version>
            </AppElement>
          </AppElement>
          <InheritPath>1J2YK+/SZ28M</InheritPath>
        </AppMetadata>
      </DataXml>
      <Description></Description>
      <DbRoute>secd</DbRoute>
      <Isv>test</Isv>
      <OpenType>0</OpenType>
      <AllUserApp>0</AllUserApp>
      <Number>test_chen_ext</Number>
      <IndustryId>0</IndustryId>
      <Id>1J95XPMF5PN3</Id>
      <Seq>2</Seq>
      <CreateDate>1618366045000</CreateDate>
      <MainFormType>0</MainFormType>
      <BizCloudID>WR/+=X74SFD</BizCloudID>
      <DependencyID></DependencyID>
      <Image>icons/pc/application/gongyingxietong_48_48.png</Image>
      <OrgFunc></OrgFunc>
      <Visible>1</Visible>
      <ModifyDate>1618475402000</ModifyDate>
      <Dependency></Dependency>
      <HelpURL></HelpURL>
      <Label></Label>
      <ModelType>AppModel</ModelType>
      <MainFormName>CHEN_应用首页</MainFormName>
      <ParentId>1J2YK+/SZ28M</ParentId>
      <BackImage></BackImage>
      <HomeURL></HomeURL>
      <MasterId>1J2YK+/SZ28M</MasterId>
      <Creater>1132523617100234752</Creater>
      <MainFormID>1J2YK+NM2YOJ</MainFormID>
      <SimpleNumber></SimpleNumber>
      <InheritPath>1J2YK+/SZ28M</InheritPath>
      <RefAppId></RefAppId>
      <UserType>1</UserType>
      <DeployStatus>2</DeployStatus>
    </DesignAppMeta>
  </DesignMetas>
  <BOSVersion>1.0</BOSVersion>
</DeployAppMetadata>
